/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poly2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import poly.Helper;
import poly.MonHoc;

/**
 *
 * @author NamCun
 */
public class Form1 extends javax.swing.JFrame {

    Connection cn;
    DefaultTableModel model = new DefaultTableModel();

    public Form1() {
        initComponents();
        setLocationRelativeTo(null);
        cn = Helper.ketnoi("TestAss1");
        if (cn != null) {
            // JOptionPane.showMessageDialog(this, "Kết nối thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Lỗi kết nối");
            System.exit(0);
        }
        model = (DefaultTableModel) tblSinhVien.getModel();
        loadDataToTable();//Lấy dữ liệu từ CSDL => Đổ lên Table
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSinhVien = new javax.swing.JTable();
        btnTTSSV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SV", "Họ Tên", "Giới tính", "Mã Môn", "Tên Môn", "Điểm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSinhVien.setRowHeight(25);
        tblSinhVien.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblSinhVien);

        btnTTSSV.setText("TTSV");
        btnTTSSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTTSSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(btnTTSSV)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTTSSV, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTTSSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTTSSVActionPerformed
        try {
            int index = tblSinhVien.getSelectedRow();
            if(index>=0){
                String masv= model.getValueAt(index, 0).toString();
                String hoten= model.getValueAt(index, 1).toString();
                String mamh= model.getValueAt(index, 3).toString();                
                float diem= (float) model.getValueAt(index, 5);
                new Form2(masv, hoten, mamh, diem, cn).setVisible(true);
            }else{
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn SV");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi TTSV");
        }
    }//GEN-LAST:event_btnTTSSVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTTSSV;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSinhVien;
    // End of variables declaration//GEN-END:variables

    private void loadDataToTable() {//Lấy dữ liệu từ CSDL => Đổ lên Table
        try {
            String sql = "select SINHVIEN.MaSV,HoTenSV,GioiTinh,MONHOC.MaMH,TenMH,diem\n"
                    + "from SINHVIEN inner join DIEM on SINHVIEN.MaSV = diem.Masv\n"
                    + "				inner join MONHOC on MONHOC.MaMH= diem.MaMH";
            
            PreparedStatement pstm = cn.prepareStatement(sql);           
            ResultSet rs = pstm.executeQuery();
            model.setRowCount(0);
            //Duyệt rs=> đổ dữ liệu vào bảng
            while (rs.next()) {
                String masv = rs.getString(1);
                String hoten = rs.getString(2);
                String gioitinh = rs.getString(3);
                String mamon = rs.getString(4);
                String tenmon = rs.getString(5);
                float diem = rs.getFloat(6);
                model.addRow(new Object[]{masv, hoten, gioitinh,mamon,tenmon,diem});
            }            
            rs.close();
            pstm.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi loadDataToTable");
        }
    }
}
