/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package slide1demo;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author WIN
 */
public class CheckNgaySinh extends javax.swing.JFrame {

    /**
     * Creates new form CheckNgaySinh
     */
    public CheckNgaySinh() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNgaySinh = new javax.swing.JTextField();
        btnCheck = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnCheck)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnCheck)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            Date d = sdf.parse(txtNgaySinh.getText().trim());
//            System.out.println("Thành công");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ngày sinh ko đúng định dạng");
            return;
        }
        //lấy năm
        Date date = new Date();
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat();
        simpleDateFormat.applyPattern("yyyy");
        String yearnow = simpleDateFormat.format(date);

        String[] mang = txtNgaySinh.getText().split("-");
        if (Integer.parseInt(mang[1]) > 12 || Integer.parseInt(mang[1]) < 1) {
            JOptionPane.showMessageDialog(this, "Tháng từ 1->12");
            return;
        }
        if (Integer.parseInt(mang[2]) > Integer.parseInt(yearnow)) {
            JOptionPane.showMessageDialog(this, "Năm phải nhỏ hơn năm hiện tại");
            return;
        }
        // xét tháng 2
        if (Integer.parseInt(mang[1]) == 2) {
            boolean isLeapYear = false;
            if (Integer.parseInt(mang[2]) % 4 == 0) {
                if (Integer.parseInt(mang[2]) % 100 == 0) {
                    if (Integer.parseInt(mang[2]) % 400 == 0) {
                        isLeapYear = true;
                    }
                } else {
                    isLeapYear = true;
                }
            }
            if (isLeapYear) {
                if (Integer.parseInt(mang[0]) != 29) {
                    JOptionPane.showMessageDialog(this, "Năm " + mang[2] + " tháng 2 có 29 ngày");
                    return;
                }
            } else {
                if (Integer.parseInt(mang[0]) != 28) {
                    JOptionPane.showMessageDialog(this, "Năm " + mang[2] + " tháng 2 có 28 ngày");
                    return;
                }
            }
        } else if (Integer.parseInt(mang[1]) == 4 || Integer.parseInt(mang[1]) == 6 || Integer.parseInt(mang[1]) == 9
                || Integer.parseInt(mang[1]) == 11) {
            if (Integer.parseInt(mang[0]) != 30) {
                JOptionPane.showMessageDialog(this, "Tháng này có 30 ngày");
                return;
            }
        } else {
            if (Integer.parseInt(mang[0]) != 31) {
                JOptionPane.showMessageDialog(this, "Tháng này có 31 ngày");
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "Thành công");
    }//GEN-LAST:event_btnCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckNgaySinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckNgaySinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckNgaySinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckNgaySinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckNgaySinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCheck;
    private javax.swing.JTextField txtNgaySinh;
    // End of variables declaration//GEN-END:variables
}
